import Apery.Measure

/-!
# The numerical inequality (6.4): `λ M₀ - I(ρ) + C* ≤ U`

Only *lower* bounds for logarithms are needed. They come from the series
`log ((1+x)/(1-x)) = 2 ∑ x^(2k+1)/(2k+1)`, whose terms are nonnegative for `0 ≤ x < 1`, so that
partial sums are lower bounds, together with Mathlib's `Real.log_two_lt_d9` for the range
reduction `log y = log (2^k y) - k log 2`. The certificates (`k`, partial sums with 10 terms,
rounded down) were generated by exact rational arithmetic; `norm_num` checks each one.
-/

open Finset

namespace Apery

/-- Lower bound for `log r`, `r ≥ 1`, by a partial sum of the artanh series. -/
lemma log_ge_artanh {r : ℝ} (hr : 1 ≤ r) (m : ℕ) :
    2 * ∑ k ∈ range m, (1 / (2 * (k : ℝ) + 1)) * ((r - 1) / (r + 1)) ^ (2 * k + 1) ≤
      Real.log r := by
  set x : ℝ := (r - 1) / (r + 1) with hx
  have hr0 : 0 < r + 1 := by linarith
  have hx0 : 0 ≤ x := div_nonneg (by linarith) hr0.le
  have hx1 : x < 1 := by rw [hx, div_lt_one hr0]; linarith
  have habs : |x| < 1 := by rw [abs_of_nonneg hx0]; exact hx1
  have hsum := Real.hasSum_log_sub_log_of_abs_lt_one habs
  have hr' : (1 + x) / (1 - x) = r := by
    rw [hx]; field_simp; ring
  have hlog : Real.log (1 + x) - Real.log (1 - x) = Real.log r := by
    rw [← Real.log_div (by linarith) (by linarith), hr']
  rw [hlog] at hsum
  have key := sum_le_hasSum (range m) (fun k _ => by
    have : 0 ≤ x ^ (2 * k + 1) := pow_nonneg hx0 _
    positivity) hsum
  rw [Finset.mul_sum]
  refine le_trans (le_of_eq ?_) key
  exact Finset.sum_congr rfl fun k _ => by ring

/-- Lower bound for `log y`, `y > 0`, after the range reduction by `2^k`. -/
lemma log_ge_of_pow_two {y : ℝ} (hy : 0 < y) (k m : ℕ) (hk : 1 ≤ 2 ^ k * y) :
    2 * ∑ j ∈ range m, (1 / (2 * (j : ℝ) + 1)) *
        ((2 ^ k * y - 1) / (2 ^ k * y + 1)) ^ (2 * j + 1) - k * 0.6931471808 ≤ Real.log y := by
  have h1 := log_ge_artanh hk m
  have h2 : Real.log (2 ^ k * y) = k * Real.log 2 + Real.log y := by
    rw [Real.log_mul (by positivity) hy.ne', Real.log_pow]
  have h3 := Real.log_two_lt_d9
  have hk0 : (0 : ℝ) ≤ k := Nat.cast_nonneg k
  nlinarith [mul_le_mul_of_nonneg_left h3.le hk0]

/-- **(6.4)**: `λ M₀ - I(ρ) + C* ≤ U`. -/
theorem energy_const : lam * M0 - Irho + Cstar ≤ (U : ℝ) := by
  have h1 : (-66675683088239 / 10000000000000 : ℝ) ≤ Real.log ((bρ 1 - aρ 1) / 4) := by
    have e : ((bρ 1 - aρ 1) / 4) = (1017189489 / 800000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 10 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h2 : (-57268912195833 / 10000000000000 : ℝ) ≤ Real.log ((bρ 2 - aρ 2) / 4) := by
    have e : ((bρ 2 - aρ 2) / 4) = (13028749591 / 4000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 9 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h3 : (-51024260463511 / 10000000000000 : ℝ) ≤ Real.log ((bρ 3 - aρ 3) / 4) := by
    have e : ((bρ 3 - aρ 3) / 4) = (24327894059 / 4000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 8 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h4 : (-22898992334719 / 5000000000000 : ℝ) ≤ Real.log ((bρ 4 - aρ 4) / 4) := by
    have e : ((bρ 4 - aρ 4) / 4) = (4102785289 / 400000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 7 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h5 : (-41154728268737 / 10000000000000 : ℝ) ≤ Real.log ((bρ 5 - aρ 5) / 4) := by
    have e : ((bρ 5 - aρ 5) / 4) = (65272891657 / 4000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 6 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h6 : (-18490372338477 / 5000000000000 : ℝ) ≤ Real.log ((bρ 6 - aρ 6) / 4) := by
    have e : ((bρ 6 - aρ 6) / 4) = (99084713271 / 4000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 6 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h7 : (-6647891986277 / 2000000000000 : ℝ) ≤ Real.log ((bρ 7 - aρ 7) / 4) := by
    have e : ((bρ 7 - aρ 7) / 4) = (144041816267 / 4000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 5 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h8 : (-239301955437 / 80000000000 : ℝ) ≤ Real.log ((bρ 8 - aρ 8) / 4) := by
    have e : ((bρ 8 - aρ 8) / 4) = (200893556541 / 4000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 5 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h9 : (-5397331999367 / 2000000000000 : ℝ) ≤ Real.log ((bρ 9 - aρ 9) / 4) := by
    have e : ((bρ 9 - aρ 9) / 4) = (269180899217 / 4000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 4 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h10 : (-24448510736217 / 10000000000000 : ℝ) ≤ Real.log ((bρ 10 - aρ 10) / 4) := by
    have e : ((bρ 10 - aρ 10) / 4) = (21684762939 / 250000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 4 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h11 : (-22286490348067 / 10000000000000 : ℝ) ≤ Real.log ((bρ 11 - aρ 11) / 4) := by
    have e : ((bρ 11 - aρ 11) / 4) = (430695182301 / 4000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 4 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h12 : (-20489791734377 / 10000000000000 : ℝ) ≤ Real.log ((bρ 12 - aρ 12) / 4) := by
    have e : ((bρ 12 - aρ 12) / 4) = (128866386789 / 1000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 3 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h13 : (-9524391997859 / 5000000000000 : ℝ) ≤ Real.log ((bρ 13 - aρ 13) / 4) := by
    have e : ((bρ 13 - aρ 13) / 4) = (595362962907 / 4000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 3 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h14 : (-17955224674931 / 10000000000000 : ℝ) ≤ Real.log ((bρ 14 - aρ 14) / 4) := by
    have e : ((bρ 14 - aρ 14) / 4) = (166040678943 / 1000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 3 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h15 : (-8601243721761 / 5000000000000 : ℝ) ≤ Real.log ((bρ 15 - aρ 15) / 4) := by
    have e : ((bρ 15 - aρ 15) / 4) = (716086447547 / 4000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 3 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have h16 : (-16785662120803 / 10000000000000 : ℝ) ≤ Real.log ((bρ 16 - aρ 16) / 4) := by
    have e : ((bρ 16 - aρ 16) / 4) = (746565554359 / 4000000000000 : ℝ) := by
      simp [aρ, bρ, table1]; norm_num
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 3 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have hα : (-25902671664061 / 10000000000000 : ℝ) ≤ Real.log alph := by
    have e : alph = (3 / 40 : ℝ) := by
      norm_num [alph]
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 4 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have hl : (1537964097723 / 2500000000000 : ℝ) ≤ Real.log (2 * lam) := by
    have e : (2 * lam) = (37 / 20 : ℝ) := by
      norm_num [lam]
    rw [e]
    refine le_trans ?_ (log_ge_of_pow_two (by norm_num) 0 10 (by norm_num))
    simp only [Finset.sum_range_succ, Finset.sum_range_zero]
    norm_num
  have hS0 : Sρ 0 = (0 : ℝ) := by
    simp [Sρ]
  have hS1 : Sρ 1 = (525779809 / 50000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS2 : Sρ 2 = (39987333973 / 1000000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS3 : Sρ 3 = (323912887 / 3906250000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS4 : Sρ 4 = (70562965519 / 500000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS5 : Sρ 5 = (52540888087 / 250000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS6 : Sρ 6 = (289036651537 / 1000000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS7 : Sρ 7 = (46736596531 / 125000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS8 : Sρ 8 = (739662167 / 1600000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS9 : Sρ 9 = (1101184473 / 2000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS10 : Sρ 10 = (127212911551 / 200000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS11 : Sρ 11 = (714963741993 / 1000000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS12 : Sρ 12 = (785317213911 / 1000000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS13 : Sρ 13 = (422078095263 / 500000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS14 : Sρ 14 = (55536094477 / 62500000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS15 : Sρ 15 = (919040377423 / 1000000000000 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hS16 : Sρ 16 = (37 / 40 : ℝ) := by
    simp [Sρ, cρ, table1, Finset.sum_Icc_succ_top]; norm_num
  have hI : Irho = ((276444407552076481 / 2500000000000000000000 : ℝ)) * Real.log ((bρ 1 - aρ 1) / 4) + ((1488409115247409372329 / 1000000000000000000000000 : ℝ)) * Real.log ((bρ 2 - aρ 2) / 4) + ((1055404259743817139291 / 200000000000000000000000 : ℝ)) * Real.log ((bρ 3 - aρ 3) / 4) + ((652026011717750304813 / 50000000000000000000000 : ℝ)) * Real.log ((bρ 4 - aρ 4) / 4) + ((1212609516209410227783 / 50000000000000000000000 : ℝ)) * Real.log ((bρ 5 - aρ 5) / 4) + ((7874693439238125629853 / 200000000000000000000000 : ℝ)) * Real.log ((bρ 6 - aρ 6) / 4) + ((11250723841514726902227 / 200000000000000000000000 : ℝ)) * Real.log ((bρ 7 - aρ 7) / 4) + ((73915179740055157667121 / 1000000000000000000000000 : ℝ)) * Real.log ((bρ 8 - aρ 8) / 4) + ((5724212864942206439 / 64000000000000000000 : ℝ)) * Real.log ((bρ 9 - aρ 9) / 4) + ((4057052429519671935601 / 40000000000000000000000 : ℝ)) * Real.log ((bρ 10 - aρ 10) / 4) + ((13324378841571167621503 / 125000000000000000000000 : ℝ)) * Real.log ((bρ 11 - aρ 11) / 4) + ((51538073291163213039 / 488281250000000000000 : ℝ)) * Real.log ((bρ 12 - aρ 12) / 4) + ((19175309507686616048151 / 200000000000000000000000 : ℝ)) * Real.log ((bρ 13 - aρ 13) / 4) + ((19242580043687170786687 / 250000000000000000000000 : ℝ)) * Real.log ((bρ 14 - aρ 14) / 4) + ((11013044231138638563501 / 200000000000000000000000 : ℝ)) * Real.log ((bρ 15 - aρ 15) / 4) + ((10989784666189711879071 / 1000000000000000000000000 : ℝ)) * Real.log ((bρ 16 - aρ 16) / 4) := by
    simp only [Irho, Finset.sum_Icc_succ_top (show 1 ≤ 16 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 15 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 14 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 13 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 12 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 11 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 10 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 9 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 8 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 7 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 6 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 5 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 4 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 3 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 2 by norm_num), Finset.sum_Icc_succ_top (show 1 ≤ 1 by norm_num), Finset.Icc_self, Finset.sum_singleton]
    simp only [hS0, hS1, hS2, hS3, hS4, hS5, hS6, hS7, hS8, hS9, hS10, hS11, hS12, hS13, hS14, hS15, hS16]
    norm_num
  rw [hI]
  unfold Cstar
  norm_num [U, M0, lam, alph] at *
  linarith

end Apery
