import pickle, math, sys
from fractions import Fraction as Fr
P=pickle.load(open('pieces.pkl','rb'))
exec(open('table.py').read().split("def Ein")[0])
al=Fr(3,40)
def lit(r):
    r=Fr(r)
    if r.denominator==1:
        return f"({r.numerator} : ℝ)" if r>=0 else f"(({r.numerator}) : ℝ)"
    return f"(({r.numerator}) / {r.denominator} : ℝ)"
forms={ (0,0):None,(0,1):None,(0,2):None,(1,0):None,(2,0):None,(1,1):None,(1,2):None,(2,1):None,(2,2):None}
def cc_val(f,g,i,j): return ccount(f,g,i,j)
def lin_of(fn,x0,x1):
    xa=x0+(x1-x0)/3; xb=x0+2*(x1-x0)/3
    ya,yb=fn(xa),fn(xb)
    a=(yb-ya)/(xb-xa); b=ya-a*xa
    return a,b
def linexpr(a,b):
    return f"({lit(a)} * x + {lit(b)})"
def piece_lemma(idx,x0,x1,k,a,b):
    q=math.floor(x0); qq=math.floor(al*x0); mu=math.floor(Fr(37,20)*x0)
    assert -2*q-6<=k<=8*q+20
    L=[]
    L.append(f"theorem inPiece_{idx} (x : ℝ) (h1 : {lit(x0)} ≤ x) (h2 : x < {lit(x1)}) :")
    L.append(f"    Ein x ({k}) = {lit(a)} * x + {lit(b)} := by")
    L.append(f"  rw [Ein_expand ({k}) (q := {q}) (q' := {qq}) (μ := {mu}) (by norm_num; linarith) (by norm_num; linarith)")
    L.append(f"    (by norm_num; linarith) (by norm_num; linarith) (by norm_num; linarith) (by norm_num; linarith) (by linarith)]")
    L.append(f"  have hf0 : (0 : ℝ) ≤ x - (({q} : ℕ) : ℝ) := by norm_num; linarith")
    L.append(f"  have hf1 : x - (({q} : ℕ) : ℝ) < 1 := by norm_num; linarith")
    L.append(f"  have hg0 : (0 : ℝ) ≤ 3 / 40 * x - (({qq} : ℕ) : ℝ) := by norm_num; linarith")
    L.append(f"  have hg1 : 3 / 40 * x - (({qq} : ℕ) : ℝ) < 1 := by norm_num; linarith")
    for (i,j) in forms:
        fn=lambda x,i=i,j=j: cc_val(x-q, al*x-qq, i, j)
        ca,cb=lin_of(fn,x0,x1)
        L.append(f"  have e{i}{j} : ccount (x - (({q} : ℕ) : ℝ)) (3 / 40 * x - (({qq} : ℕ) : ℝ)) {i} {j} = {linexpr(ca,cb)} := by")
        L.append(f"    rw [cc{i}{j} hf0 hf1 hg0 hg1]; (try simp only [min_def, max_def]); (try split_ifs) <;> (push_cast at *; linarith)")
    L.append("  simp only [Fin.sum_univ_three]")
    L.append("  rw [e00, e01, e02, e10, e11, e12, e20, e21, e22]")
    L.append("  simp only [bIn, bcoef, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two,")
    L.append("    Matrix.head_cons, Matrix.tail_cons, psiR_eq, lrow, toNat_cast_q]")
    L.append("  push_cast")
    L.append("  norm_num")
    L.append("  ring")
    return "\n".join(L)
if __name__=="__main__":
    n=int(sys.argv[1]) if len(sys.argv)>1 else len(P)
    out=["import Mathlib","import Apery.Growth.TableGen","","set_option linter.unusedSimpArgs false","set_option linter.unusedTactic false","","/-! Generated by `gen_lean_inner.py`: the pieces of `Ê_in` on `[3, 20]`. -/","","namespace Apery",""]
    for idx,(x0,x1,k,a,b) in enumerate(P[:n]):
        out.append(piece_lemma(idx,x0,x1,k,a,b)); out.append("")
    out.append("end Apery")
    open('InnerTableTest.lean','w').write("\n".join(out))
