import pickle, math
from fractions import Fraction as Fr
P=pickle.load(open('pieces.pkl','rb'))
def q_lit(r):
    r=Fr(r)
    return f"({r.numerator})" if r.denominator==1 else f"({r.numerator}/{r.denominator})"
ts=[p[0] for p in P]+[P[-1][1]]
out=["import Mathlib","import Apery.Growth.InnerTable","","set_option linter.unusedSimpArgs false","set_option linter.unusedTactic false","set_option maxHeartbeats 4000000","",
"/-! Generated by `gen_inner_sum.py`: the table of `Ê_in` on `[3, 20]`. -/","","namespace Apery",""]
out.append("def tInL : List ℚ := ["+", ".join(q_lit(t) for t in ts)+"]")
out.append("def kInL : List ℤ := ["+", ".join(str(p[2]) for p in P)+"]")
out.append("def aInL : List ℚ := ["+", ".join(q_lit(p[3]) for p in P)+"]")
out.append("def bInL : List ℚ := ["+", ".join(q_lit(p[4]) for p in P)+"]")
out.append("")
out.append("noncomputable def tIn (i : ℕ) : ℝ := ((tInL.getD i 0 : ℚ) : ℝ)")
out.append("def kIn (i : ℕ) : ℤ := kInL.getD i 0")
out.append("noncomputable def gIn (i : ℕ) (x : ℝ) : ℝ := ((aInL.getD i 0 : ℚ) : ℝ) * x + ((bInL.getD i 0 : ℚ) : ℝ)")
out.append("")
out.append(f"theorem tIn_mono : ∀ i < {len(P)}, tIn i < tIn (i + 1) := by")
out.append("  intro i hi")
out.append("  interval_cases i <;> simp only [tIn, tInL, List.getD_cons_succ, List.getD_cons_zero] <;> norm_num")
out.append("")
out.append(f"theorem inner_table : ∀ i < {len(P)}, ∀ x ∈ Set.Ico (tIn i) (tIn (i + 1)), Ein x (kIn i) = gIn i x := by")
out.append("  intro i hi x hx")
out.append("  interval_cases i")
for idx in range(len(P)):
    out.append(f"  · simp only [tIn, tInL, kIn, kInL, gIn, aInL, bInL, List.getD_cons_succ, List.getD_cons_zero, Set.mem_Ico] at hx ⊢")
    out.append(f"    push_cast at hx ⊢")
    out.append(f"    have := inPiece_{idx} x (by linarith [hx.1]) (by linarith [hx.2])")
    out.append(f"    linarith")
out.append("")
# admissibility of k: 2 <= k and k <= 8 q + 20 where q = floor of t_i
out.append(f"theorem inner_table_k : ∀ i < {len(P)}, ∀ x ∈ Set.Ico (tIn i) (tIn (i + 1)),")
out.append("    -2 * (⌊x⌋₊ : ℤ) - 6 ≤ kIn i ∧ kIn i ≤ 8 * (⌊x⌋₊ : ℤ) + 20 := by")
out.append("  intro i hi x hx")
out.append("  interval_cases i")
for idx,(x0,x1,k,a,b) in enumerate(P):
    q=math.floor(x0)
    assert -2*q-6<=k<=8*q+20
    out.append(f"  · simp only [tIn, tInL, kIn, kInL, List.getD_cons_succ, List.getD_cons_zero, Set.mem_Ico] at hx ⊢")
    out.append(f"    push_cast at hx")
    out.append(f"    rw [nat_floor_of_bounds (q := {q}) (by norm_num; linarith [hx.1]) (by norm_num; linarith [hx.2])]")
    out.append(f"    norm_num")
out.append("")
out.append("end Apery")
open('InnerSum.lean','w').write("\n".join(out))
