import pickle, math
from fractions import Fraction as Fr
exec(open('outer_gen.py').read().split("lo,hi=")[0])
P=pickle.load(open('outer_pieces.pkl','rb'))
def lit(r):
    r=Fr(r)
    if r.denominator==1:
        return f"({r.numerator} : ℝ)" if r>=0 else f"(({r.numerator}) : ℝ)"
    return f"(({r.numerator}) / {r.denominator} : ℝ)"
def q_lit(r):
    r=Fr(r)
    return f"({r.numerator})" if r.denominator==1 else f"({r.numerator}/{r.denominator})"
def lin_of(fn,x0,x1):
    xa=x0+(x1-x0)/3; xb=x0+2*(x1-x0)/3
    ya,yb=fn(xa),fn(xb)
    a=(yb-ya)/(xb-xa); b=ya-a*xa
    return a,b
def linexpr(a,b): return f"({lit(a)} * x + {lit(b)})"
al=Fr(3,40)
out=["import Mathlib","import Apery.Growth.TableGen","","set_option linter.unusedSimpArgs false","set_option linter.unusedTactic false","set_option maxHeartbeats 4000000","",
"/-! Generated by `gen_lean_outer.py`: the table of `Ê_out` on `[20/37, 3]`. -/","","namespace Apery",""]
for idx,(x0,x1,a,b) in enumerate(P):
    q=math.floor(x0); qq=math.floor(al*x0); mu=math.floor(Fr(37,20)*x0)
    L=[]
    L.append(f"theorem outPiece_{idx} (x : ℝ) (h1 : {lit(x0)} ≤ x) (h2 : x < {lit(x1)}) :")
    L.append(f"    Eout x = {lit(a)} * x + {lit(b)} := by")
    L.append(f"  rw [Eout_expand (q := {q}) (q' := {qq}) (μ := {mu}) (by norm_num; linarith) (by norm_num; linarith)")
    L.append(f"    (by norm_num; linarith) (by norm_num; linarith) (by norm_num; linarith) (by norm_num; linarith) (by linarith)]")
    L.append(f"  have hf0 : (0 : ℝ) ≤ x - (({q} : ℕ) : ℝ) := by norm_num; linarith")
    L.append(f"  have hf1 : x - (({q} : ℕ) : ℝ) < 1 := by norm_num; linarith")
    L.append(f"  have hg0 : (0 : ℝ) ≤ 3 / 40 * x - (({qq} : ℕ) : ℝ) := by norm_num; linarith")
    L.append(f"  have hg1 : 3 / 40 * x - (({qq} : ℕ) : ℝ) < 1 := by norm_num; linarith")
    for (i,j) in [(0,0),(0,1),(0,2),(1,0),(1,1),(1,2),(2,0),(2,1),(2,2)]:
        fn=lambda x,i=i,j=j: ccount(x-q, al*x-qq, i, j)
        ca,cb=lin_of(fn,x0,x1)
        L.append(f"  have e{i}{j} : ccount (x - (({q} : ℕ) : ℝ)) (3 / 40 * x - (({qq} : ℕ) : ℝ)) {i} {j} = {linexpr(ca,cb)} := by")
        L.append(f"    rw [cc{i}{j} hf0 hf1 hg0 hg1]; (try simp only [min_def, max_def]); (try split_ifs) <;> (push_cast at *; linarith)")
    fn=lambda x: max(Fr(0),Fr(13,10)*x-2)
    ca,cb=lin_of(fn,x0,x1)
    L.append(f"  have em : max 0 (13 / 10 * x - 2) = {linexpr(ca,cb)} := by")
    L.append(f"    (try simp only [max_def]); (try split_ifs) <;> linarith")
    L.append("  simp only [Fin.sum_univ_three]")
    L.append("  rw [e00, e01, e02, e10, e11, e12, e20, e21, e22, em]")
    L.append("  simp only [bGO, bcoef, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two,")
    L.append("    Matrix.head_cons, Matrix.tail_cons, GO, Finset.sum_range_succ, Finset.sum_range_zero]")
    L.append("  norm_num")
    L.append("  ring_nf")
    out.append("\n".join(L)); out.append("")
ts=[p[0] for p in P]+[P[-1][1]]
out.append("def tOutL : List ℚ := ["+", ".join(q_lit(t) for t in ts)+"]")
out.append("def aOutL : List ℚ := ["+", ".join(q_lit(p[2]) for p in P)+"]")
out.append("def bOutL : List ℚ := ["+", ".join(q_lit(p[3]) for p in P)+"]")
out.append("noncomputable def tOut (i : ℕ) : ℝ := ((tOutL.getD i 0 : ℚ) : ℝ)")
out.append("noncomputable def gOut (i : ℕ) (x : ℝ) : ℝ := ((aOutL.getD i 0 : ℚ) : ℝ) * x + ((bOutL.getD i 0 : ℚ) : ℝ)")
out.append("")
out.append(f"theorem tOut_mono : ∀ i < {len(P)}, tOut i < tOut (i + 1) := by")
out.append("  intro i hi")
out.append("  interval_cases i <;> simp only [tOut, tOutL, List.getD_cons_succ, List.getD_cons_zero] <;> norm_num")
out.append("")
out.append(f"theorem outer_table : ∀ i < {len(P)}, ∀ x ∈ Set.Ico (tOut i) (tOut (i + 1)), Eout x = gOut i x := by")
out.append("  intro i hi x hx")
out.append("  interval_cases i")
for idx in range(len(P)):
    out.append(f"  · simp only [tOut, tOutL, gOut, aOutL, bOutL, List.getD_cons_succ, List.getD_cons_zero, Set.mem_Ico] at hx ⊢")
    out.append(f"    push_cast at hx ⊢")
    out.append(f"    have := outPiece_{idx} x (by linarith [hx.1]) (by linarith [hx.2])")
    out.append(f"    linarith")
out.append("")
out.append("end Apery")
open('OuterTable.lean','w').write("\n".join(out))
print(len(P), [ (float(p[0]),float(p[1])) for p in P])
